language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.11"
  - "0.12"
  - "iojs"
bundler_args:
  --retry 3
script: "npm run-script cover-test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"